infra-geo-ouverte/sdg

- packages/sdg/src/lib/core/style/overrides/material/_button-theme.scss
- projects/demo/src/app/app.component.scss
- projects/demo/src/app/components/example-viewer/example-viewer.component.scss
- projects/demo/src/app/components/external-link/external-link.component.html
- projects/demo/src/app/components/external-link/external-link.component.scss
- projects/demo/src/app/components/external-link/external-link.component.spec.ts
- projects/demo/src/app/components/external-link/external-link.component.ts
- projects/demo/src/app/pages/components/showcases/button/button.component.html
- projects/demo/src/app/pages/components/showcases/button/button.component.scss
- projects/demo/src/app/pages/components/showcases/button/button.component.spec.ts
- projects/demo/src/app/pages/components/showcases/button/button.component.ts
- projects/demo/src/app/pages/components/showcases/showcases.component.html
- projects/demo/src/app/pages/components/showcases/showcases.component.scss
- projects/demo/src/app/pages/components/showcases/showcases.component.ts
- projects/demo/src/app/pages/components/showcases/showcases.routes.ts
L'ajout d'un exemple d'utilisation d'un bouton dans le showcase de la démo
Quelques modifications au showcases pour permettre la navigation entre les pages de démonstration
> feat(showcases): add button example

- packages/sdg/src/lib/core/style/overrides/igo2-lib/scrollbar.scss
- packages/sdg/src/lib/core/style/overrides/igo2-lib/search-bar.scss
- packages/sdg/src/lib/core/style/overrides/material/input.scss
- packages/sdg/src/lib/core/theme/_colors.scss
- packages/sdg/src/lib/core/theme/_palettes.scss
- packages/sdg/src/lib/core/typography/typography.scss
- packages/sdg/src/lib/core/typography/typography.utils.scss
- packages/sdg/src/lib/header/header.component.scss
- packages/sdg/src/lib/navigation/navigation.component.scss
Ajouté les couleurs en plus des bleus (gris, jaunes, rouges, etc.). Ajustements un peu partout dans le code pour refléter les ajouts/chagements.
> feat(colors): added and changed colors

- projects/demo/src/app/components/external-link/external-link.component.html
- projects/demo/src/app/components/external-link/external-link.component.scss
- projects/demo/src/app/pages/components/showcases/button/button.component.html
- projects/demo/src/app/pages/components/showcases/button/button.component.scss
Ajusté l'alignement du texte descriptif dans la démo.
> fix(button): fix alignment text demo

- projects/demo/src/index.html
Changé les symboles pour les mettre en contour comme dans le SDG.
> refactor(symbols): changed to outline

- packages/sdg/src/lib/tile/index.ts
- packages/sdg/src/lib/tile/tile.component.html
- packages/sdg/src/lib/tile/tile.component.scss
- packages/sdg/src/lib/tile/tile.component.spec.ts
- packages/sdg/src/lib/tile/tile.component.ts
- packages/sdg/src/public-api.ts
- projects/demo/src/app/pages/components/showcases/showcases.routes.ts
- projects/demo/src/app/pages/components/showcases/tile/tile.component.html
- projects/demo/src/app/pages/components/showcases/tile/tile.component.scss
- projects/demo/src/app/pages/components/showcases/tile/tile.component.spec.ts
- projects/demo/src/app/pages/components/showcases/tile/tile.component.ts
Nouvelle composante de tuile cliquable. Ajout à la démo.
> feat(tile): added tile component

- packages/sdg/src/lib/alert/alert.component.ts
- packages/sdg/src/lib/notice/notice.component.ts
- packages/sdg/src/lib/tile/tile.component.ts
- projects/demo/src/app/pages/about/about.component.html
- projects/demo/src/app/pages/components/showcases/alert/alert.component.html
- projects/demo/src/app/pages/components/showcases/breadcrumb/breadcrumb.component.html
- projects/demo/src/app/pages/components/showcases/breadcrumb/breadcrumb.component.spec.ts
- projects/demo/src/app/pages/components/showcases/breadcrumb/breadcrumb.component.ts
- projects/demo/src/app/pages/components/showcases/button/button.component.html
- projects/demo/src/app/pages/components/showcases/button/button.component.spec.ts
- projects/demo/src/app/pages/components/showcases/button/button.component.ts
- projects/demo/src/app/pages/components/showcases/notice/notice.component.html
- projects/demo/src/app/pages/components/showcases/notice/notice.component.spec.ts
- projects/demo/src/app/pages/components/showcases/showcases.routes.ts
- projects/demo/src/app/pages/components/showcases/tile/tile.component.html
J'ai enlevé certains imports qui étaient pas utilisés pour le moment comme IgoLanguageModule. J'ai renommé le composant des boutons et des breadcrumbs en ajoutant Demo pour éviter la confusion.
> refactor(various): removed unused modules and various adjustments

- packages/sdg/src/lib/consult/consult.component.html
- packages/sdg/src/lib/consult/consult.component.scss
- packages/sdg/src/lib/consult/consult.component.spec.ts
- packages/sdg/src/lib/consult/consult.component.ts
- packages/sdg/src/lib/consult/index.ts
- packages/sdg/src/lib/consult/link.interface.ts
- packages/sdg/src/lib/core/typography/typography.scss
- packages/sdg/src/public-api.ts
- projects/demo/src/app/pages/components/showcases/consult/consult.component.html
- projects/demo/src/app/pages/components/showcases/consult/consult.component.spec.ts
- projects/demo/src/app/pages/components/showcases/consult/consult.component.ts
- projects/demo/src/app/pages/components/showcases/showcases.routes.ts
Nouveau composant À consulter aussi. Ajout à la démo.
> feat(consult): add consult component

- packages/sdg/src/lib/tile/tile.component.html
- packages/sdg/src/lib/tile/tile.component.scss
- projects/demo/src/app/pages/components/showcases/tile/tile.component.spec.ts
Passage de div à button, Ajustements de style
> refactor(tile): tile adjustments

- packages/sdg/src/lib/tile/tile.component.html
- packages/sdg/src/lib/tile/tile.component.scss
- projects/demo/src/app/pages/components/showcases/showcases.component.html
- projects/demo/src/app/pages/components/showcases/showcases.component.ts
- projects/demo/src/app/pages/components/showcases/tile/tile.component.spec.ts
Passage de `li` à `li` avec `a` intégré pour être comme `components.component` et rendre les élément focusable,
> refactor(showcases): li to li-a

- eslint.config.js
- packages/geo/src/legend/legend-button/legend-button.component.ts
- packages/src/lib/anchor-menu/anchor-menu.component.ts
- packages/src/lib/navigation/navigation.component.ts
- packages/src/lib/paginator/paginator.component.ts
- packages/src/lib/sequential-links/sequential-links.component.ts
- packages/src/lib/tile/tile.component.ts
- projects/demo/src/app/pages/about/about.component.ts
- projects/demo/src/app/pages/components/components.component.ts
- projects/demo/src/app/pages/components/showcases/alert/alert.component.ts
- projects/demo/src/app/pages/components/showcases/anchor-menu/anchor-menu.component.ts
- projects/demo/src/app/pages/components/showcases/consult/consult.component.ts
- projects/demo/src/app/pages/components/showcases/notice/notice.component.ts
- projects/demo/src/app/pages/components/showcases/paginator/paginator.component.ts
- projects/demo/src/app/pages/components/showcases/sequential-links/sequential-links.component.ts
- projects/demo/src/app/pages/components/showcases/showcases.component.ts
- projects/demo/src/app/pages/components/showcases/tile/tile.component.ts
- projects/demo/src/app/pages/contact-us/contact-us.component.ts
- projects/demo/src/app/pages/guides/guides.component.ts
Proposition de standardisé la façon dont nos classes sont structuré et ordonnés dans le but de faciliter la lecture et la navigation.
Ordre proposé:
1. Propriétés
2. Constructeur
3. Méthodes
> chore(eslint): add member ordering for consistency

- packages/src/lib/consult/consult.component.spec.ts
- packages/src/lib/navigation/navigation.component.spec.ts
- projects/demo/src/app/components/example-viewer/example-viewer.component.ts
- projects/demo/src/app/pages/components/showcases/alert/alert.component.spec.ts
- projects/demo/src/app/pages/components/showcases/button/button.component.spec.ts
- projects/demo/src/app/pages/components/showcases/consult/consult.component.spec.ts
- projects/demo/src/app/pages/components/showcases/notice/notice.component.spec.ts
- projects/demo/src/app/pages/components/showcases/paginator/paginator.component.html
Nettoyage des fichiers .spec.ts pour uniformité.
> chore: cleaned tests

- packages/src/lib/contact/contact.component.html
- packages/src/lib/contact/contact.component.scss
- packages/src/lib/contact/contact.component.spec.ts
- packages/src/lib/contact/contact.component.ts
- packages/src/lib/contact/contact.interface.ts
- packages/src/lib/contact/contact.ts
- packages/src/lib/contact/index.ts
- packages/src/public-api.ts
- projects/demo/src/app/pages/components/showcases/contact/contact-custom.ts
- projects/demo/src/app/pages/components/showcases/contact/contact.component.html
- projects/demo/src/app/pages/components/showcases/contact/contact.component.scss
- projects/demo/src/app/pages/components/showcases/contact/contact.component.spec.ts
- projects/demo/src/app/pages/components/showcases/contact/contact.component.ts
- projects/demo/src/app/pages/components/showcases/showcases.routes.ts
Nouveau composant de coordonnées. Ajout à la démo
> feat(contact): add contact component

- packages/core/src/router/index.ts
- packages/core/src/router/route.interface.ts
- packages/core/src/router/route.utils.ts
- packages/src/lib/block-link/block-link-subsection/block-link-subsection.component.html
- packages/src/lib/block-link/block-link-subsection/block-link-subsection.component.scss
- packages/src/lib/block-link/block-link-subsection/block-link-subsection.component.spec.ts
- packages/src/lib/block-link/block-link-subsection/block-link-subsection.component.ts
- packages/src/lib/block-link/block-link.component.html
- packages/src/lib/block-link/block-link.component.scss
- packages/src/lib/block-link/block-link.component.spec.ts
- packages/src/lib/block-link/block-link.component.ts
- packages/src/lib/block-link/block-link.interface.ts
- packages/src/lib/block-link/index.ts
- packages/src/public-api.ts
- projects/demo/src/app/pages/components/components.component.html
- projects/demo/src/app/pages/components/components.component.ts
- projects/demo/src/app/pages/components/showcases/block-link/block-link.component.html
- projects/demo/src/app/pages/components/showcases/block-link/block-link.component.scss
- projects/demo/src/app/pages/components/showcases/block-link/block-link.component.spec.ts
- projects/demo/src/app/pages/components/showcases/block-link/block-link.component.ts
- projects/demo/src/app/pages/components/showcases/showcases.routes.ts
Nouveau composant de lien en bloc. Ajout à la démo.
Modification de components.component de la démo pour utiliser ce composant.
> feat(block-link): add block-link component

- packages/core/src/layout/breakpoint/breakpoint.service.spec.ts
- packages/core/src/layout/breakpoint/breakpoint.service.ts
- packages/core/src/layout/breakpoint/index.ts
- packages/core/src/layout/index.ts
- packages/core/src/public-api.ts
- packages/core/src/style/overrides/material/_button-theme.scss
- packages/core/src/style/overrides/material/button.scss
- packages/geo/src/map/map-browser/map-browser.component.scss
- packages/src/lib/navigation/_navigation-theme.scss
- packages/src/lib/navigation/index.ts
- packages/src/lib/navigation/navigation.component.html
- packages/src/lib/navigation/navigation.component.scss
- packages/src/lib/navigation/navigation.component.spec.ts
- packages/src/lib/navigation/navigation.component.ts
- packages/src/lib/navigation/navigation.interface.ts
- packages/src/lib/navigation/navigation.utils.ts
- packages/src/lib/screen/split-screen/split-screen.component.html
- projects/demo/public/locale/en.json
- projects/demo/public/locale/fr.json
- projects/demo/src/app/app.component.html
- projects/demo/src/app/app.component.spec.ts
- projects/demo/src/app/app.component.ts
- projects/demo/src/app/app.config.ts
- projects/demo/src/app/pages/components/components.component.scss
- projects/demo/src/app/pages/components/showcases/navigation/navigation.component.html
- projects/demo/src/app/pages/components/showcases/navigation/navigation.component.spec.ts
- projects/demo/src/app/pages/components/showcases/navigation/navigation.component.ts
- projects/demo/src/app/pages/components/showcases/showcases.routes.ts
- projects/demo/src/environments/environment.interface.ts
Continuation de l'implémentation de la composante de navigation:
- Ajustement des styles pour les mise en page desktop et mobile
- Gestion de l'overflow avec le bouton Plus
- Ajout de tests
> feat(navigation): continue implementation

- packages/core/src/style/overrides/material/input.scss
- packages/core/src/typography/typography.scss
- packages/core/src/typography/typography.utils.scss
- packages/src/lib/alert/alert.component.scss
- packages/src/lib/anchor-menu/anchor-menu.component.scss
- packages/src/lib/consult/consult.component.scss
- packages/src/lib/contact/contact.component.scss
- packages/src/lib/navigation/navigation.component.scss
- packages/src/lib/notice/notice.component.scss
- packages/src/lib/sequential-links/sequential-links.component.scss
- packages/src/lib/tile/tile.component.scss
- projects/demo/src/theme/theme.scss
Retrait de l'import `sass:map` où inutilsé.
> fix: removed unused sass import

- projects/demo/src/app/app.component.ts
- projects/demo/src/app/pages/about/about.component.ts
- projects/demo/src/app/pages/components/components.component.ts
- projects/demo/src/app/pages/components/showcases/alert/alert.component.ts
- projects/demo/src/app/pages/components/showcases/anchor-menu/anchor-menu.component.ts
- projects/demo/src/app/pages/components/showcases/block-link/block-link.component.ts
- projects/demo/src/app/pages/components/showcases/consult/consult.component.ts
- projects/demo/src/app/pages/components/showcases/contact/contact.component.ts
- projects/demo/src/app/pages/components/showcases/header/header.component.ts
- projects/demo/src/app/pages/components/showcases/notice/notice.component.ts
- projects/demo/src/app/pages/components/showcases/paginator/paginator.component.ts
- projects/demo/src/app/pages/components/showcases/sequential-links/sequential-links.component.ts
- projects/demo/src/app/pages/components/showcases/tile/tile.component.ts
- projects/demo/src/app/pages/contact-us/contact-us.component.ts
- projects/demo/src/app/pages/guides/guides.component.ts
Passage à `BreakpointService` au lieu de `AppService`
> fix: appservice to breakpointservice

- packages/src/lib/tile/tile.component.html
- packages/src/lib/tile/tile.component.scss
- projects/demo/src/app/pages/components/showcases/tile/tile.component.html
- projects/demo/src/app/pages/components/showcases/tile/tile.component.scss
Modification du nom de la classe `handset` pour cohérence entre les composants.
> fix: handset class name

- projects/demo/src/app/pages/components/components.component.html
- projects/demo/src/app/pages/components/showcases/anchor-menu/anchor-menu.component.html
- projects/demo/src/app/pages/components/showcases/block-link/block-link.component.html
- projects/demo/src/app/pages/components/showcases/consult/consult.component.html
- projects/demo/src/app/pages/components/showcases/navigation/navigation.component.html
- projects/demo/src/app/pages/components/showcases/notice/notice.component.html
- projects/demo/src/app/pages/components/showcases/notice/notice.component.scss
- projects/demo/src/app/pages/components/showcases/paginator/paginator.component.html
- projects/demo/src/app/pages/components/showcases/sequential-links/sequential-links.component.html
- projects/demo/src/app/pages/components/showcases/tile/tile.component.html
Retrait des balises superflues et autres petits correctifs.
> fix: cleaned demo html files

- packages/src/lib/footer/footer-copyright/footer-copyright.component.ts
- packages/src/lib/footer/footer-links/footer-links.component.ts
> fix: cleaned footer imports

- packages/geo/src/screen/map-screen/map-screen-panel/map-screen-panel.component.spec.ts
- packages/src/lib/breadcrumbs/breadcrumbs-item/breadcrumbs-item.component.spec.ts
- packages/src/lib/breadcrumbs/breadcrumbs-list/breadcrumbs-list.component.spec.ts
- packages/src/lib/breadcrumbs/breadcrumbs-menu/breadcrumbs-menu.component.spec.ts
- packages/src/lib/navigation/navigation.component.spec.ts
- projects/demo/src/app/components/example-viewer/example-viewer.component.spec.ts
- projects/demo/src/app/components/screen/basic-screen/basic-screen.component.spec.ts
- projects/demo/src/app/components/screen/split-screen/split-screen.component.spec.ts
- projects/demo/src/app/config/translation/translation.service.spec.ts
- projects/demo/src/app/pages/about/about.component.spec.ts
- projects/demo/src/app/pages/components/components.component.spec.ts
- projects/demo/src/app/pages/components/showcases/anchor-menu/anchor-menu.component.spec.ts
- projects/demo/src/app/pages/components/showcases/block-link/block-link.component.spec.ts
- projects/demo/src/app/pages/components/showcases/breadcrumbs/breadcrumbs.component.spec.ts
- projects/demo/src/app/pages/components/showcases/showcases.component.spec.ts
- projects/demo/src/app/pages/guides/guides.component.spec.ts
Nettoyage des fichiers `spec.ts` pour uniformisation.
> fix: updates spec.ts import

- packages/src/lib/block-link/block-link-icon/block-link-icon.component.html
- packages/src/lib/block-link/block-link-icon/block-link-icon.component.scss
- packages/src/lib/block-link/block-link-icon/block-link-icon.component.spec.ts
- packages/src/lib/block-link/block-link-icon/block-link-icon.component.ts
- packages/src/lib/block-link/block-link-see-more/block-link-see-more.component.html
- packages/src/lib/block-link/block-link-see-more/block-link-see-more.component.scss
- packages/src/lib/block-link/block-link-see-more/block-link-see-more.component.spec.ts
- packages/src/lib/block-link/block-link-see-more/block-link-see-more.component.ts
- packages/src/lib/block-link/block-link-subsection/block-link-subsection.component.html
- packages/src/lib/block-link/block-link-subsection/block-link-subsection.component.scss
- packages/src/lib/block-link/block-link-title-description/block-link-title-description.component.html
- packages/src/lib/block-link/block-link-title-description/block-link-title-description.component.scss
- packages/src/lib/block-link/block-link-title-description/block-link-title-description.component.spec.ts
- packages/src/lib/block-link/block-link-title-description/block-link-title-description.component.ts
- packages/src/lib/block-link/block-link.component.html
- packages/src/lib/block-link/block-link.component.scss
- packages/src/lib/block-link/block-link.component.spec.ts
- packages/src/lib/block-link/block-link.component.ts
- packages/src/lib/block-link/block-link.interface.ts
- packages/src/lib/shared/anchor/anchor.component.html
- packages/src/lib/shared/anchor/anchor.component.spec.ts
- packages/src/lib/shared/anchor/anchor.component.ts
- projects/demo/src/app/pages/components/components.component.scss
- projects/demo/src/app/pages/components/components.component.ts
- projects/demo/src/app/pages/components/showcases/block-link/block-link.component.html
- projects/demo/src/app/pages/components/showcases/block-link/block-link.component.scss
- projects/demo/src/app/pages/components/showcases/block-link/block-link.component.ts
Nettoyage du composant, renommage des classes.
Description facultative avec liens, ajout d'une variante avec icône.
> fix: cleaned block-link component

- packages/src/lib/notice/notice.component.html
- packages/src/lib/notice/notice.component.scss
- packages/src/lib/notice/notice.component.spec.ts
- packages/src/lib/notice/notice.component.ts
Nettoyage du composant, renommage des classes.
> fix: cleaned notice component

- packages/src/lib/block-link/block-link-see-more/block-link-see-more.component.html
- packages/src/lib/block-link/block-link-see-more/block-link-see-more.component.spec.ts
- packages/src/lib/block-link/block-link-see-more/block-link-see-more.component.ts
- packages/src/lib/block-link/block-link-title-description/block-link-title-description.component.html
- packages/src/lib/block-link/block-link-title-description/block-link-title-description.component.scss
- packages/src/lib/block-link/block-link.component.html
- packages/src/lib/block-link/block-link.interface.ts
- projects/demo/public/locale/en.json
- projects/demo/public/locale/fr.json
- projects/demo/src/app/pages/components/components.component.scss
- projects/demo/src/app/pages/components/components.component.ts
- projects/demo/src/app/pages/components/showcases/block-link/block-link.component.ts
Correction de la position de la flèche du titre du lien en bloc à la fin d'un titre long.
Label de Voir plus en input et input pour titre foncé.
> fix(common): fixed block-link title arrow

- package-lock.json
- packages/src/lib/breadcrumbs/breadcrumbs-base.ts
- packages/src/lib/header/header.component.ts
- packages/src/lib/lateral-menu/lateral-menu.component.ts
- packages/src/lib/navigation/navigation.component.ts
- packages/src/lib/paginator/paginator.component.ts
- projects/demo/src/app/app.component.ts
- projects/demo/src/app/pages/components/showcases/showcases.component.ts
- tsconfig.json
On avait une propriété qui divergeait de QEA-CLIENT et lorsqu'on lançait en symlink ça ne fonctionnait plus.
> fix: use before it's initialization

- packages/src/lib/top-page-button/index.ts
- packages/src/lib/top-page-button/top-page-button.component.html
- packages/src/lib/top-page-button/top-page-button.component.scss
- packages/src/lib/top-page-button/top-page-button.component.spec.ts
- packages/src/lib/top-page-button/top-page-button.component.ts
- packages/src/public-api.ts
- projects/demo/public/locale/en.json
- projects/demo/public/locale/fr.json
- projects/demo/src/app/app.component.html
- projects/demo/src/app/app.component.scss
- projects/demo/src/app/app.component.ts
- projects/demo/src/app/pages/components/showcases/showcases.routes.ts
- projects/demo/src/app/pages/components/showcases/top-page-button/top-page-button.component.html
- projects/demo/src/app/pages/components/showcases/top-page-button/top-page-button.component.scss
- projects/demo/src/app/pages/components/showcases/top-page-button/top-page-button.component.spec.ts
- projects/demo/src/app/pages/components/showcases/top-page-button/top-page-button.component.ts
- projects/demo/src/styles.scss
Nouveau composant de bouton haut de page.
> feat: added top page button component

- packages/carto/src/ol/reference-map/reference-map.component.ts
Ajout d'un output pour reference-map
> fix: added reference map output

- packages/carto/src/ol/reference-map/reference-map.component.html
- packages/carto/src/ol/reference-map/reference-map.component.scss
- packages/src/lib/alert/alert.component.scss
- packages/src/lib/anchor-menu/anchor-menu.component.html
- packages/src/lib/anchor-menu/anchor-menu.component.scss
- packages/src/lib/block-link/block-link-title-description/block-link-title-description.component.scss
- packages/src/lib/breadcrumbs/breadcrumbs-item/breadcrumbs-item.component.scss
- packages/src/lib/contact/contact.component.html
- packages/src/lib/contact/contact.component.scss
- packages/src/lib/header/header.component.scss
- packages/src/lib/lateral-menu/lateral-menu-item/lateral-menu-item.component.html
- packages/src/lib/lateral-menu/lateral-menu-item/lateral-menu-item.component.scss
- packages/src/lib/lateral-menu/lateral-menu-section/lateral-menu-section.component.html
- packages/src/lib/lateral-menu/lateral-menu-section/lateral-menu-section.component.scss
- packages/src/lib/lateral-menu/lateral-menu.component.html
- packages/src/lib/lateral-menu/lateral-menu.component.scss
- packages/src/lib/notice/notice.component.scss
- packages/src/lib/paginator/paginator.component.html
- packages/src/lib/paginator/paginator.component.scss
- packages/src/lib/sequential-links/sequential-links.component.html
- packages/src/lib/sequential-links/sequential-links.component.scss
- packages/src/lib/tile/tile.component.html
- packages/src/lib/tile/tile.component.scss
- projects/demo/src/app/components/screen/split-screen/split-screen.component.scss
- projects/demo/src/app/pages/components/components.component.scss
- projects/demo/src/app/pages/components/showcases/block-link/block-link.component.scss
- projects/demo/src/app/pages/components/showcases/tile/tile.component.scss
Normalisation du nom des classes pour tous les composants restants et nettoyage (excluant geo).
Correction de la taille de police pour `sdg-anchor-menu`
> fix: normalized styling and classes

- packages/common/src/anchor-menu/anchor-menu.component.scss
- packages/core/src/layout/_breakpoints.scss
- packages/core/src/typography/typography.scss
Changement de style pour la typographie
> fix(core): typography styles

- packages/common/src/anchor-menu/anchor-menu.component.html
- packages/common/src/anchor-menu/anchor-menu.component.scss
- packages/common/src/block-link/block-link-title-description/block-link-title-description.component.html
- packages/common/src/block-link/block-link-title-description/block-link-title-description.component.scss
- packages/common/src/breadcrumbs/breadcrumbs-item/breadcrumbs-item.component.scss
- packages/common/src/contact/contact.component.html
- packages/common/src/contact/contact.component.scss
- packages/common/src/lateral-menu/lateral-menu-section/lateral-menu-section.component.html
- packages/common/src/lateral-menu/lateral-menu-section/lateral-menu-section.component.scss
- packages/common/src/paginator/paginator.component.html
- packages/common/src/paginator/paginator.component.scss
- packages/common/src/sequential-links/sequential-links.component.html
- packages/common/src/sequential-links/sequential-links.component.scss
- packages/common/src/tile/tile.component.html
- packages/common/src/tile/tile.component.scss
- packages/core/src/typography/typography.scss
Correction des marges et changement à `<span>` lorsque nécessaire.
> fix: margins and spans

- packages/common/src/block-link/block-link-see-more/block-link-see-more.component.html
- packages/common/src/block-link/block-link-see-more/block-link-see-more.component.scss
- packages/common/src/block-link/block-link-title-description/block-link-title-description.component.html
- packages/common/src/block-link/block-link-title-description/block-link-title-description.component.scss
- packages/common/src/block-link/block-link-title-description/block-link-title-description.component.ts
- packages/common/src/block-link/block-link.component.scss
Modification du Lien en bloc.
- Retrait de la flèche rose en mobile.
- Changement d'icône pour Voir plus lorsque lien externe.
> fix: block-link styling

- packages/core/src/style/overrides/material/_index.scss
- packages/core/src/style/overrides/material/_radio-button.scss
- projects/demo/public/locale/en.json
- projects/demo/public/locale/fr.json
- projects/demo/src/app/components/example-viewer/example-viewer.component.ts
- projects/demo/src/app/pages/components/showcases/radio-button/radio-button.component.html
- projects/demo/src/app/pages/components/showcases/radio-button/radio-button.component.scss
- projects/demo/src/app/pages/components/showcases/radio-button/radio-button.component.spec.ts
- projects/demo/src/app/pages/components/showcases/radio-button/radio-button.component.ts
- projects/demo/src/app/pages/components/showcases/showcases.routes.ts
Nouveau composant de bouton radio pour les formulaires.
> feat: added radio button component

- packages/common/src/analytics/google-analytics/google-analytics.provider.spec.ts
- packages/common/src/analytics/google-analytics/google-analytics.provider.ts
- packages/common/src/analytics/google-analytics/google-analytics.service.spec.ts
- packages/common/src/analytics/google-analytics/google-analytics.service.ts
fix(common): google analytics - gtag blocking ssr hydratation run outside zone
> fix(common): google analytics - custom first page view for ssr only
